---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

Layout/LineLength:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2
