---
name: CI

on:
  pull_request: {}
  push:
    branches:
      - master

permissions:
  contents: read

env:
  BEAKER_HYPERVISOR: docker

jobs:
  rubocop_and_matrix:
    runs-on: ubuntu-latest
    outputs:
      ruby: ${{ steps.ruby.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rake rubocop
      - id: ruby
        uses: voxpupuli/ruby-version@v1

  build:
    runs-on: ubuntu-latest
    needs: rubocop_and_matrix
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJSON(needs.rubocop_and_matrix.outputs.ruby) }}
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Run acceptance tests
        run: bundle exec rake acceptance

  tests:
    needs:
      - build
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
